version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Prod"
s3_bucket = "sam-app-deployment-template-bucket"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"