version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume"
s3_bucket = "resume-sam-deployment-bucket"
s3_prefix = "cloud-resume"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"