version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
region = "us-east-1"
s3_bucket = "sam-app-deployment-template-bucket"
s3_prefix = "sam-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"